name: Release

on:
  push:
    tags:
      - "*"

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2

      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
        with:
          path: .

      - name: Upload PyInstaller Output
        uses: actions/upload-artifact@v4.3.1
        with:
          name: pyinstaller-output
          path: ./dist

  windows-build-and-release:
    permissions:
      contents: write
    runs-on: windows-latest
    needs: ubuntu-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2

      - name: Download PyInstaller Output
        uses: actions/download-artifact@v4.1.4
        with:
          name: pyinstaller-output
          path: ./dist

      - name: Inno Setup Action
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
        with:
          path: bot_setup.iss

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: windows_installer.exe
          generate_release_notes: true