name: Release

on:
  push:
    tags:
      - "*"

jobs:
  windows-build-and-release:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Versatile PyInstaller
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          spec: bot.spec
          requirements: requirements.txt
          python_ver: "3.12"
          clean_checkout: false

      - name: Inno Setup Action
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: bot_setup.iss

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: windows_installer.exe
          generate_release_notes: true