name: Automatic repo changes on creation

on:
  create:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out the code
      uses: actions/checkout@v4.1.5

    - name: Make changes
      run: |
        sed -i "s/%REPO_NAME%/${{ github.event.repository.name }} - Discord Bot/g" bot_setup.iss
        sed -i "s/%APP_ID%/$(uuidgen)/g" bot_setup.iss
        sed -i "s/%REPO_OWNER%/${{ github.event.repository.owner.login }}/g" bot_setup.iss
        rm -f .github/workflows/repo-creation.yml

    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        push: origin HEAD:master
        default_author: github_actions
        message: "setup: replace placeholders, remove setup workflow"